-- USED_GOODS_BOARD(BOARD_ID) // USED_GOODS_REPLY(REPLY_ID) -- BOARD_ID WRITER_ID
-- 2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일

SELECT TITLE, B.BOARD_ID, REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") CREATED_DATE
  FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
 WHERE B.BOARD_ID = R.BOARD_ID
   AND DATE_FORMAT(B.CREATED_DATE, "%Y-%m") = "2022-10"
 ORDER BY R.CREATED_DATE ASC, TITLE ASC;